/**
 * Lista curada y estática de marcas comunes en el mercado chileno —
 * fuente de sugerencias para el autocompletado de "Marca" (Fase 3,
 * Agregar vehículo). No existe ningún catálogo real en el backend
 * (`brand` es texto libre en `CreateVehicleDto`); esta lista nunca
 * valida ni bloquea, solo sugiere.
 */
export const VEHICLE_BRANDS: readonly string[] = [
  'Toyota',
  'Chevrolet',
  'Nissan',
  'Hyundai',
  'Kia',
  'Suzuki',
  'Mazda',
  'Ford',
  'Volkswagen',
  'Peugeot',
  'Renault',
  'Citroën',
  'Fiat',
  'Honda',
  'Mitsubishi',
  'Subaru',
  'Great Wall',
  'GWM',
  'Changan',
  'JAC',
  'Chery',
  'MG',
  'BYD',
  'Volvo',
  'BMW',
  'Mercedes-Benz',
  'Audi',
  'Jeep',
  'RAM',
  'Dodge',
  'Chrysler',
  'Mini',
  'Land Rover',
  'Jaguar',
  'Porsche',
  'SsangYong',
  'Foton',
  'JMC',
  'Maxus',
  'DFSK',
  'Baic',
  'Haval',
  'Isuzu',
  'Mahindra',
  'Alfa Romeo',
  'SEAT',
  'Škoda',
  'Lexus',
  'Infiniti',
  'Acura',
  'Cadillac',
  'GMC',
] as const;
